executor: "KubernetesExecutor"

# Images
images:
  airflow:
    repository: my-dags
    tag: ~
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true

    repo: https://github.com/vitordarcidasilva/databricks-airflow-k8s.git
    branch: main
    rev: HEAD
    ref: main
    depth: 1
    maxFailures: 0
    subPath: "dags"
    credentialsSecret: git-credentials

logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: True
    # If using a custom storageClass, pass name here
    storageClassName: manual
    ## the name of an existing PVC to use
    existingClaim: airflow-logs-pvc