apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # Path on the container host, where logs will be stored
    path: /mnt/airflow-data/logs
